schema_version: 1

context:
  name: girder-worker
  version: "5.0.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/girder_worker-${{ version }}.tar.gz
  sha256: aa7cca7086ebdde25f5defc9714234d81bcc01447990c087bab4a5f58062ea64

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=${{ python_min }}
    - pyyaml >=4.2b1
    - jinja2 >=2.10.1
    - urllib3 >=1.26.8
    - celery
    - girder-client >=5.0.0a5
    - pymongo >=3
    - requests >=2.20.0
    - setuptools-scm
    - stevedore
    - jsonpickle
    - docker-py >=2.6.0

tests:
  - python:
      imports:
        - girder_worker
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Batch execution engine built on celery.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/girder/girder_worker

extra:
  recipe-maintainers:
    - jan-janssen
